---
abstract: 'Base implementations for modules to negotiate with Google Data APIs'
author:
  - 'Nobuo Danjou <nobuo.danjou@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-DataAPI
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Moose: 0.56
requires:
  Any::Moose: 0.04
  Carp: 0
  Digest::SHA1: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Lingua::EN::Inflect::Number: 0
  Mouse: 0.51
  Net::Google::AuthSub: 0.5
  Net::OAuth: 0
  Text::Glob: 0
  URI: 0
  XML::Atom: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lopnor/Net-Google-DataAPI.git
version: 0.25
