---
abstract: 'Base implementations for modules to negotiate with Google Data APIs'
author:
  - 'Nobuo Danjou <nobuo.danjou@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::MockModule: 0
  Test::MockObject: 0
  Test::More: 0.88
  Test::Warn: 0
  UNIVERSAL::can: 0
  UNIVERSAL::isa: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-DataAPI
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Mouse: 0.51
requires:
  Any::Moose: 0.04
  Carp: 0
  Crypt::SSLeay: 0
  Digest::SHA1: 0
  LWP::UserAgent: 0
  Lingua::EN::Inflect::Number: 0
  Moose: 0.56
  Net::Google::AuthSub: 0.5
  Net::OAuth: 0
  URI: 0
  XML::Atom: 0
  namespace::autoclean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lopnor/Net-Google-DataAPI.git
version: 0.17
